import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Make sure this file contains your Tailwind CSS and other global styles
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";
// Load Inter font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dynamic Blog",  // Page title
  description: "Generated by create next app",  // Page description
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Add any other meta tags here if needed */}
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>

        </body> {/* Renders the content of each page here */}
    </html>
  );
}
